import pandas as pd
df = pd.read_excel('dirty_titanic_df.xlsx')
df.head(10)
df.info()
df.describe(include='all')
df['Survived'].dtype
df['Survived'] = df['Survived'].astype('bool')
df['Pclass'].nunique()
df['Pclass'] = df['Pclass'].astype(‘category’)
df.insert(4, 'Title', '')
df['Title'] = df['Name'].str.split(',', expand = True)
df = df.drop(columns = ['Name'])
df.head(10)
df['Title'].unique() 
pd.crosstab(df['Title'], df['Sex'])
df['Title'] = df['Title'].replace(['Lady ', 'Countess ','Capt ', 'Col ','Dr ', 'Major ', 'Rev', 'Sir'], 'Rare')
df['Title'] = df['Title'].replace('Mlle ', 'Miss')
df['Title'] = df['Title'].replace('Ms ', 'Miss')
df['Title'] = df['Title'].replace('Mme ', 'Mrs')
df['Title'].unique()
title_mapping = {"Mr": 1, "Miss": 2, "Mrs": 3, "Master": 4, "Rare": 5}
df['Title'] = df['Title'].map(title_mapping)
df['Title'] = df['Title'].fillna(0)
df['Title'] = df['Title'].round(0).astype(int)
pd.crosstab(df[‘Title’], data[‘Sex’])
women = df.loc[df['Sex'] == 'female']["Survived"]
rate_women = sum(women)/len(women)
men = df.loc[data['Sex'] == 'male']["Survived"]
rate_men = sum(men)/len(men)
print("% of women who survived:", rate_women)
print("% of men who survived:", rate_men)
df['Age'].isnull().sum()
df.sort_values('Age',ascending=False).head(10)
df['Age'].min()
df['Age].max()
df['Age'].describe()
df['Age].dtype
df['Age']=pd.to_numeric(df['Age'],errors='coerce')
df.head(10)
df['Age'] = df['Age'].fillna((df['Age'].median()))
df['Age'] = df['Age'].astype(int)
df.head(10)
df[['SibSp', 'Survived']].groupby(['SibSp'], as_index=False).mean().sort_values(by='Survived', ascending=False)
df[['Parch', 'Survived']].groupby(['Parch'], as_index=False).mean().sort_values(by='Survived', ascending=False)
df = df.drop(labels=['Ticket'], axis=1)
df.sort_values('Fare',ascending=False)
df['Fare'] = df['Fare'].round(2)
df.head(10)
df = df.drop(labels=['Cabin'],axis=1)
df.head(10)
freq_port = df['Embarked'].dropna().mode()[0]
df['Embarked'] = df['Embarked'].fillna(freq_port)  
df[['Embarked', 'Survived']].groupby(['Embarked'], 
as_index=False).mean().sort_values(by='Survived', ascending=False)
df['Embarked'] = df['Embarked'].map( {'S': 0, 'C': 1, 'Q': 
2}).astype(int)
data.head(10)